# Generated by Django 5.2.11 on 2026-02-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('message', models.EmailField(max_length=254)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
